// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsvuBEuF8UC7zNdtkmeVneWmxoIpXGvy0',
    appId: '1:398366770184:web:45c3c1d44572d2dde87dbd',
    messagingSenderId: '398366770184',
    projectId: 'whatsapp-9798a',
    authDomain: 'whatsapp-9798a.firebaseapp.com',
    storageBucket: 'whatsapp-9798a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2nOu51ihHbcI4X3UcOB3BqDDLs1LoL-g',
    appId: '1:398366770184:android:7848b1b2c5f19c5be87dbd',
    messagingSenderId: '398366770184',
    projectId: 'whatsapp-9798a',
    storageBucket: 'whatsapp-9798a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHOtRH0HrPEpuALqeBpfWSrBWipCtAEz4',
    appId: '1:398366770184:ios:26975d7800ec5dbee87dbd',
    messagingSenderId: '398366770184',
    projectId: 'whatsapp-9798a',
    storageBucket: 'whatsapp-9798a.appspot.com',
    androidClientId: '398366770184-egvcmptomjfv9nb33ggp2p33crnjb3s0.apps.googleusercontent.com',
    iosClientId: '398366770184-t03ptrnvmfmv97v1scl1vaj6abj4ogsr.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappClone',
  );
}
